# Generated by Django 4.2.3 on 2023-08-20 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_arenaimg_banner_bobur_boburarena_ceremony_pride_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bobur',
            name='img',
        ),
        migrations.AddField(
            model_name='bobur',
            name='img',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.img'),
            preserve_default=False,
        ),
    ]
