# Generated by Django 4.2.3 on 2023-08-20 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_bobur_img_bobur_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bobur',
            name='img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.arenaimg'),
        ),
    ]
